import React, {useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, Check, ChevronDown, CircleHelp, Clock3, LockKeyhole, MessageCircleQuestion, Play, RotateCcw, Search, Send, ShieldCheck, Sparkles, Users, X} from 'lucide-react';
import {DISCLOSURES, STATUSES, drawCandidate, publicAuthor, validateQuestion} from './domain.js';
import {load,save,reset} from './store.js';
import {drawQuestion, finishQuestion, listQuestions, moderateQuestion, seedTestQuestions, submitQuestion} from './api.js';
import './styles.css';

const pages=['submit','admin','stage'];
function route(){ const p=location.hash.slice(1).split('?')[0]; return pages.includes(p)?p:'submit'; }
function App(){ const [page,setPage]=useState(route()); useEffect(()=>{ const f=()=>setPage(route()); addEventListener('hashchange',f); return()=>removeEventListener('hashchange',f)},[]); return <>{page==='submit'?<Submit/>:page==='admin'?<Admin/>:<Stage/>}</> }
function Brand({dark=false}){return <a className={'brand '+(dark?'brand-dark':'')} href="#submit"><span className="brand-mark">G</span><span>강남, 묻고 답하다<small>직원 정례조례</small></span></a>}
function Submit(){
 const [form,setForm]=useState({text:'',department:'',position:'',name:'',disclosure:'ANONYMOUS'}),[busy,setBusy]=useState(false),[done,setDone]=useState(null),[error,setError]=useState('');
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 const submit=async e=>{e.preventDefault(); const err=validateQuestion(form.text); if(err){setError(err);return} setBusy(true);setError('');try{const result=await submitQuestion({...form,text:form.text.trim()});setDone(result.id)}catch(error){setError(error instanceof Error?error.message:'질문 접수에 실패했습니다. 잠시 후 다시 시도해 주세요.')}finally{setBusy(false)}};
 if(done)return <main className="submit-page"><SubmitHeader/><section className="success-card"><span className="success-icon"><Check/></span><p className="eyebrow">질문 접수 완료</p><h1>소중한 질문을<br/>보내주셔서 감사합니다.</h1><p>운영진 검토 후 정례조례 현장에서 소개될 수 있어요.</p><div className="receipt"><span>접수 번호</span><strong>{done}</strong></div><button className="btn secondary" onClick={()=>{setDone(null);setForm({text:'',department:'',position:'',name:'',disclosure:'ANONYMOUS'})}}>질문 하나 더 보내기</button></section></main>;
 return <main className="submit-page"><SubmitHeader/><div className="submit-wrap"><section className="intro"><p className="eyebrow">SEPTEMBER TOWN HALL</p><h1>구청장님께<br/>지금 가장 궁금한<br/><em>한 가지는?</em></h1><p className="lead">가벼운 질문도, 진지한 제안도 좋습니다.<br/>정해진 주제나 정답은 없어요.</p><div className="prompt-chips"><span>일하는 방식</span><span>조직문화</span><span>직원복지</span><span>강남의 미래</span></div></section><form className="question-form" onSubmit={submit}><div className="form-head"><span><MessageCircleQuestion/></span><div><h2>질문을 들려주세요</h2><p>작성한 원문은 수정되지 않습니다.</p></div></div><label>질문 <b>필수</b><textarea maxLength="500" value={form.text} onChange={e=>{set('text',e.target.value);setError('')}} placeholder="지금 떠오른 질문을 자유롭게 적어주세요."/><small className={error?'field-error':''}>{error||`${form.text.length} / 500자`}</small></label><div className="three-cols"><Input label="부서명" value={form.department} onChange={v=>set('department',v)} placeholder="선택 입력"/><Input label="직급" value={form.position} onChange={v=>set('position',v)} placeholder="선택 입력"/><Input label="이름" value={form.name} onChange={v=>set('name',v)} placeholder="선택 입력"/></div><fieldset><legend>공개 범위 <b>필수</b></legend>{Object.entries(DISCLOSURES).map(([v,label])=><label className={'radio '+(form.disclosure===v?'selected':'')} key={v}><input type="radio" checked={form.disclosure===v} onChange={()=>set('disclosure',v)}/><span><strong>{label}</strong><small>{v==='ANONYMOUS'?'어떤 정보도 공개하지 않아요':v==='DEPARTMENT'?'부서명만 함께 소개해요':'입력한 정보를 함께 소개해요'}</small></span><Check/></label>)}</fieldset><aside className="privacy"><ShieldCheck/><p><strong>안심하고 질문해 주세요.</strong><br/>개인정보, 연락처, 민감정보나 특정인을 식별할 수 있는 내용은 질문에 적지 말아 주세요.</p></aside><button disabled={busy} className="btn primary">{busy?'접수하고 있어요…':<>질문 보내기 <Send/></>}</button></form></div></main>
}
function SubmitHeader(){return <header className="topbar"><Brand/><span className="status-dot">질문 접수 중</span></header>}
function Input({label,value,onChange,placeholder}){return <label>{label}<input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}

function Admin(){
 const [questions,setQuestions]=useState([]),[filter,setFilter]=useState('ALL'),[query,setQuery]=useState(''),[pin,setPin]=useState(()=>sessionStorage.getItem('operator-pin')||''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const refresh=async(value=pin)=>{if(!value)return;setBusy(true);setError('');try{setQuestions(await listQuestions(value))}catch(e){setError(e.message)}finally{setBusy(false)}};
 const enterPin=()=>{const value=window.prompt('운영자 PIN을 입력하세요.','');if(value){sessionStorage.setItem('operator-pin',value);setPin(value);refresh(value)}};
 useEffect(()=>{if(pin)refresh(pin)},[]);
 const counts=useMemo(()=>Object.fromEntries(Object.keys(STATUSES).map(k=>[k,questions.filter(q=>q.status===k).length])),[questions]);
 const list=questions.filter(q=>(filter==='ALL'||q.status===filter)&&q.text.includes(query));
 const update=async(id,status)=>{setBusy(true);setError('');try{await moderateQuestion(pin,id,status);await refresh(pin)}catch(e){setError(e.message);setBusy(false)}};
 const seed=async()=>{if(!confirm('Google Sheet에 테스트 질문 100개를 추가할까요?'))return;setBusy(true);setError('');try{const result=await seedTestQuestions(pin,100);alert(`테스트 질문 ${result.count}개를 생성했습니다. 승인 질문은 ${result.approved}개입니다.`);await refresh(pin)}catch(e){setError(e.message);setBusy(false)}};
 return <main className="admin-page"><aside className="sidebar"><Brand dark/><nav><a className="active"><MessageCircleQuestion/>질문 검토</a><a href="#stage"><Play/>행사 화면</a></nav><div className="side-note"><LockKeyhole/><span>운영자 전용<br/><small>Google Sheet 연동</small></span></div></aside><section className="admin-main"><header><div><p className="eyebrow">QUESTION DESK</p><h1>질문 검토</h1>{error&&<p className="field-error">{error}</p>}</div><div className="card-actions"><button onClick={pin?seed:enterPin} disabled={busy}>{pin?'테스트 질문 100개 생성':'운영자 PIN 입력'}</button><a className="stage-link" href="#stage">행사 화면 열기 <ArrowRight/></a></div></header><div className="stats"><Stat label="전체 질문" n={questions.length} tone="dark"/><Stat label="새 질문" n={counts.SUBMITTED||0}/><Stat label="승인" n={counts.APPROVED||0} tone="green"/><Stat label="보류·제외" n={(counts.HELD||0)+(counts.EXCLUDED||0)} tone="orange"/><Stat label="추첨 완료" n={counts.DRAWN||0} tone="purple"/></div><div className="toolbar"><div className="tabs"><button className={filter==='ALL'?'active':''} onClick={()=>setFilter('ALL')}>전체</button>{Object.entries(STATUSES).map(([v,l])=><button className={filter===v?'active':''} onClick={()=>setFilter(v)} key={v}>{l}</button>)}</div><label className="search"><Search/><input placeholder="질문 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="question-list">{list.map(q=><article className="review-card" key={q.id}><div className="card-meta"><span className={'badge '+q.status.toLowerCase()}>{STATUSES[q.status]}</span><span>{q.id}</span><span><Clock3/> {new Date(q.createdAt).toLocaleDateString('ko-KR')}</span></div><h3>{q.text}</h3><div className="display-preview"><small>행사 화면 표시</small><p>{q.displayText}</p><span>{publicAuthor(q)} · {DISCLOSURES[q.disclosure]}</span></div><div className="card-actions"><button disabled={busy} onClick={()=>update(q.id,'APPROVED')}><Check/> 승인</button><button disabled={busy} onClick={()=>update(q.id,'HELD')}><Clock3/> 보류</button><button disabled={busy} onClick={()=>update(q.id,'EXCLUDED')} className="danger"><X/> 제외</button></div></article>)}{!list.length&&<div className="empty">{busy?'Google Sheet에서 불러오는 중입니다.':pin?'조건에 맞는 질문이 없습니다.':'운영자 PIN을 입력해 주세요.'}</div>}</div></section></main>}
function Stat({label,n,tone=''}){return <div className={'stat '+tone}><span>{label}</span><strong>{n}</strong></div>}

function Stage(){
 const [pin,setPin]=useState(()=>sessionStorage.getItem('operator-pin')||''),[eligible,setEligible]=useState(0),[drawing,setDrawing]=useState(false),[current,setCurrent]=useState(null),[error,setError]=useState('');
 const refresh=async(value=pin)=>{if(!value)return;try{const questions=await listQuestions(value);setEligible(questions.filter(q=>q.status==='APPROVED'&&!q.drawOrder).length)}catch(e){setError(e.message)}};
 const enterPin=()=>{const value=window.prompt('운영자 PIN을 입력하세요.','');if(value){sessionStorage.setItem('operator-pin',value);setPin(value);refresh(value)}};
 useEffect(()=>{if(pin)refresh(pin)},[]);
 const draw=async()=>{if(drawing||!eligible||!pin)return;setDrawing(true);setCurrent(null);setError('');try{const [pick]=await Promise.all([drawQuestion(pin),new Promise(resolve=>setTimeout(resolve,1800))]);if(pick){setCurrent({id:pick.id,displayText:pick.text,author:pick.author,drawOrder:pick.order});setEligible(n=>Math.max(0,n-1))}}catch(e){setError(e.message)}finally{setDrawing(false)}};
 const finish=async status=>{try{await finishQuestion(pin,current.id,status);setCurrent(null);await refresh(pin)}catch(e){setError(e.message)}};
 return <main className={'stage '+(drawing?'is-drawing':'')}><header><Brand dark/><span>2026년 9월 직원 정례조례</span><a href="#admin">운영 화면</a></header><div className="orb orb-a"/><div className="orb orb-b"/><section className="stage-content">{error&&<p className="field-error">{error}</p>}{!current&&!drawing&&<><p className="stage-kicker"><Sparkles/> 오늘의 질문</p><h1>우리의 생각을 잇는<br/><em>한 가지 질문</em></h1>{!pin?<button className="draw-button" onClick={enterPin}><span><LockKeyhole/></span>운영자 PIN 입력</button>:<button className="draw-button" onClick={draw} disabled={!eligible}><span><Play fill="currentColor"/></span>{eligible?'질문 뽑기':'모든 질문을 뽑았어요'}</button>}<p className="candidate-count"><Users/> 승인된 미추첨 질문 {eligible}개</p></>}{drawing&&<div className="draw-animation"><div className="dice"><i/><i/><i/><i/><i/></div><h1>질문을 고르고 있습니다</h1><p>잠시만 기다려 주세요</p></div>}{current&&!drawing&&<div className="reveal"><p className="stage-kicker">QUESTION {String(current.drawOrder).padStart(2,'0')}</p><blockquote>“{current.displayText}”</blockquote><p className="author">{current.author}</p><div className="stage-actions"><button onClick={()=>finish('ANSWERED')}><Check/> 답변 완료</button><button onClick={()=>finish('HELD')}><Clock3/> 현장 보류</button></div></div>}</section><footer><span>GANGNAM-GU OFFICE</span><span>Google Sheet 기반 중복 방지 추첨</span></footer></main>}
createRoot(document.getElementById('root')).render(<App/>);
